/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutUsSection {
    }
    interface AcmeChatButton {
    }
    interface AcmeContactForm {
    }
    interface AcmeFooter {
    }
    interface AcmeHeader {
    }
    interface AcmeNavbar {
        /**
          * string that identifies the nav class
         */
        "navBarClass": string;
    }
    interface AcmeSections {
    }
    interface AcmeSubnav {
    }
    interface AcmeWebsite {
    }
    interface AppMobileSection {
    }
    interface BannerSection {
    }
    interface BusinessSection {
    }
    interface CardsSection {
    }
    interface DivServizio {
        /**
          * service's description
         */
        "description": string;
        /**
          * attribute name to choose the ionicon
         */
        "iconName": string;
        /**
          * service's title
         */
        "label": string;
    }
    interface NewsSection {
    }
    interface SingleCard {
        /**
          * card description
         */
        "descrizione": string;
        /**
          * image file name
         */
        "fileName": string;
        /**
          * what is written inside the clickable tag a at the bottom of the card
         */
        "scrittaBottone": string;
        /**
          * card subtitle
         */
        "titoletto": string;
        /**
          * card title
         */
        "titolo": string;
    }
    interface WhatYouNeedSection {
    }
}
declare global {
    interface HTMLAboutUsSectionElement extends Components.AboutUsSection, HTMLStencilElement {
    }
    var HTMLAboutUsSectionElement: {
        prototype: HTMLAboutUsSectionElement;
        new (): HTMLAboutUsSectionElement;
    };
    interface HTMLAcmeChatButtonElement extends Components.AcmeChatButton, HTMLStencilElement {
    }
    var HTMLAcmeChatButtonElement: {
        prototype: HTMLAcmeChatButtonElement;
        new (): HTMLAcmeChatButtonElement;
    };
    interface HTMLAcmeContactFormElement extends Components.AcmeContactForm, HTMLStencilElement {
    }
    var HTMLAcmeContactFormElement: {
        prototype: HTMLAcmeContactFormElement;
        new (): HTMLAcmeContactFormElement;
    };
    interface HTMLAcmeFooterElement extends Components.AcmeFooter, HTMLStencilElement {
    }
    var HTMLAcmeFooterElement: {
        prototype: HTMLAcmeFooterElement;
        new (): HTMLAcmeFooterElement;
    };
    interface HTMLAcmeHeaderElement extends Components.AcmeHeader, HTMLStencilElement {
    }
    var HTMLAcmeHeaderElement: {
        prototype: HTMLAcmeHeaderElement;
        new (): HTMLAcmeHeaderElement;
    };
    interface HTMLAcmeNavbarElement extends Components.AcmeNavbar, HTMLStencilElement {
    }
    var HTMLAcmeNavbarElement: {
        prototype: HTMLAcmeNavbarElement;
        new (): HTMLAcmeNavbarElement;
    };
    interface HTMLAcmeSectionsElement extends Components.AcmeSections, HTMLStencilElement {
    }
    var HTMLAcmeSectionsElement: {
        prototype: HTMLAcmeSectionsElement;
        new (): HTMLAcmeSectionsElement;
    };
    interface HTMLAcmeSubnavElement extends Components.AcmeSubnav, HTMLStencilElement {
    }
    var HTMLAcmeSubnavElement: {
        prototype: HTMLAcmeSubnavElement;
        new (): HTMLAcmeSubnavElement;
    };
    interface HTMLAcmeWebsiteElement extends Components.AcmeWebsite, HTMLStencilElement {
    }
    var HTMLAcmeWebsiteElement: {
        prototype: HTMLAcmeWebsiteElement;
        new (): HTMLAcmeWebsiteElement;
    };
    interface HTMLAppMobileSectionElement extends Components.AppMobileSection, HTMLStencilElement {
    }
    var HTMLAppMobileSectionElement: {
        prototype: HTMLAppMobileSectionElement;
        new (): HTMLAppMobileSectionElement;
    };
    interface HTMLBannerSectionElement extends Components.BannerSection, HTMLStencilElement {
    }
    var HTMLBannerSectionElement: {
        prototype: HTMLBannerSectionElement;
        new (): HTMLBannerSectionElement;
    };
    interface HTMLBusinessSectionElement extends Components.BusinessSection, HTMLStencilElement {
    }
    var HTMLBusinessSectionElement: {
        prototype: HTMLBusinessSectionElement;
        new (): HTMLBusinessSectionElement;
    };
    interface HTMLCardsSectionElement extends Components.CardsSection, HTMLStencilElement {
    }
    var HTMLCardsSectionElement: {
        prototype: HTMLCardsSectionElement;
        new (): HTMLCardsSectionElement;
    };
    interface HTMLDivServizioElement extends Components.DivServizio, HTMLStencilElement {
    }
    var HTMLDivServizioElement: {
        prototype: HTMLDivServizioElement;
        new (): HTMLDivServizioElement;
    };
    interface HTMLNewsSectionElement extends Components.NewsSection, HTMLStencilElement {
    }
    var HTMLNewsSectionElement: {
        prototype: HTMLNewsSectionElement;
        new (): HTMLNewsSectionElement;
    };
    interface HTMLSingleCardElement extends Components.SingleCard, HTMLStencilElement {
    }
    var HTMLSingleCardElement: {
        prototype: HTMLSingleCardElement;
        new (): HTMLSingleCardElement;
    };
    interface HTMLWhatYouNeedSectionElement extends Components.WhatYouNeedSection, HTMLStencilElement {
    }
    var HTMLWhatYouNeedSectionElement: {
        prototype: HTMLWhatYouNeedSectionElement;
        new (): HTMLWhatYouNeedSectionElement;
    };
    interface HTMLElementTagNameMap {
        "about-us-section": HTMLAboutUsSectionElement;
        "acme-chat-button": HTMLAcmeChatButtonElement;
        "acme-contact-form": HTMLAcmeContactFormElement;
        "acme-footer": HTMLAcmeFooterElement;
        "acme-header": HTMLAcmeHeaderElement;
        "acme-navbar": HTMLAcmeNavbarElement;
        "acme-sections": HTMLAcmeSectionsElement;
        "acme-subnav": HTMLAcmeSubnavElement;
        "acme-website": HTMLAcmeWebsiteElement;
        "app-mobile-section": HTMLAppMobileSectionElement;
        "banner-section": HTMLBannerSectionElement;
        "business-section": HTMLBusinessSectionElement;
        "cards-section": HTMLCardsSectionElement;
        "div-servizio": HTMLDivServizioElement;
        "news-section": HTMLNewsSectionElement;
        "single-card": HTMLSingleCardElement;
        "what-you-need-section": HTMLWhatYouNeedSectionElement;
    }
}
declare namespace LocalJSX {
    interface AboutUsSection {
    }
    interface AcmeChatButton {
    }
    interface AcmeContactForm {
    }
    interface AcmeFooter {
    }
    interface AcmeHeader {
    }
    interface AcmeNavbar {
        /**
          * string that identifies the nav class
         */
        "navBarClass"?: string;
    }
    interface AcmeSections {
    }
    interface AcmeSubnav {
    }
    interface AcmeWebsite {
    }
    interface AppMobileSection {
    }
    interface BannerSection {
    }
    interface BusinessSection {
    }
    interface CardsSection {
    }
    interface DivServizio {
        /**
          * service's description
         */
        "description"?: string;
        /**
          * attribute name to choose the ionicon
         */
        "iconName"?: string;
        /**
          * service's title
         */
        "label"?: string;
    }
    interface NewsSection {
    }
    interface SingleCard {
        /**
          * card description
         */
        "descrizione"?: string;
        /**
          * image file name
         */
        "fileName"?: string;
        /**
          * what is written inside the clickable tag a at the bottom of the card
         */
        "scrittaBottone"?: string;
        /**
          * card subtitle
         */
        "titoletto"?: string;
        /**
          * card title
         */
        "titolo"?: string;
    }
    interface WhatYouNeedSection {
    }
    interface IntrinsicElements {
        "about-us-section": AboutUsSection;
        "acme-chat-button": AcmeChatButton;
        "acme-contact-form": AcmeContactForm;
        "acme-footer": AcmeFooter;
        "acme-header": AcmeHeader;
        "acme-navbar": AcmeNavbar;
        "acme-sections": AcmeSections;
        "acme-subnav": AcmeSubnav;
        "acme-website": AcmeWebsite;
        "app-mobile-section": AppMobileSection;
        "banner-section": BannerSection;
        "business-section": BusinessSection;
        "cards-section": CardsSection;
        "div-servizio": DivServizio;
        "news-section": NewsSection;
        "single-card": SingleCard;
        "what-you-need-section": WhatYouNeedSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-us-section": LocalJSX.AboutUsSection & JSXBase.HTMLAttributes<HTMLAboutUsSectionElement>;
            "acme-chat-button": LocalJSX.AcmeChatButton & JSXBase.HTMLAttributes<HTMLAcmeChatButtonElement>;
            "acme-contact-form": LocalJSX.AcmeContactForm & JSXBase.HTMLAttributes<HTMLAcmeContactFormElement>;
            "acme-footer": LocalJSX.AcmeFooter & JSXBase.HTMLAttributes<HTMLAcmeFooterElement>;
            "acme-header": LocalJSX.AcmeHeader & JSXBase.HTMLAttributes<HTMLAcmeHeaderElement>;
            "acme-navbar": LocalJSX.AcmeNavbar & JSXBase.HTMLAttributes<HTMLAcmeNavbarElement>;
            "acme-sections": LocalJSX.AcmeSections & JSXBase.HTMLAttributes<HTMLAcmeSectionsElement>;
            "acme-subnav": LocalJSX.AcmeSubnav & JSXBase.HTMLAttributes<HTMLAcmeSubnavElement>;
            "acme-website": LocalJSX.AcmeWebsite & JSXBase.HTMLAttributes<HTMLAcmeWebsiteElement>;
            "app-mobile-section": LocalJSX.AppMobileSection & JSXBase.HTMLAttributes<HTMLAppMobileSectionElement>;
            "banner-section": LocalJSX.BannerSection & JSXBase.HTMLAttributes<HTMLBannerSectionElement>;
            "business-section": LocalJSX.BusinessSection & JSXBase.HTMLAttributes<HTMLBusinessSectionElement>;
            "cards-section": LocalJSX.CardsSection & JSXBase.HTMLAttributes<HTMLCardsSectionElement>;
            "div-servizio": LocalJSX.DivServizio & JSXBase.HTMLAttributes<HTMLDivServizioElement>;
            "news-section": LocalJSX.NewsSection & JSXBase.HTMLAttributes<HTMLNewsSectionElement>;
            "single-card": LocalJSX.SingleCard & JSXBase.HTMLAttributes<HTMLSingleCardElement>;
            "what-you-need-section": LocalJSX.WhatYouNeedSection & JSXBase.HTMLAttributes<HTMLWhatYouNeedSectionElement>;
        }
    }
}
