/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcmeChatButton {
    }
    interface AcmeContactForm {
    }
    interface AcmeFooter {
    }
    interface AcmeHeader {
    }
    interface AcmeNavbar {
    }
    interface AcmeSections {
    }
    interface AcmeSubnav {
    }
    interface AcmeWebsite {
    }
    interface BannerSection {
    }
    interface DivServizio {
        /**
          * service's description
         */
        "description": string;
        /**
          * attribute name to choose the ionicon
         */
        "iconName": string;
        /**
          * service's title
         */
        "label": string;
    }
}
declare global {
    interface HTMLAcmeChatButtonElement extends Components.AcmeChatButton, HTMLStencilElement {
    }
    var HTMLAcmeChatButtonElement: {
        prototype: HTMLAcmeChatButtonElement;
        new (): HTMLAcmeChatButtonElement;
    };
    interface HTMLAcmeContactFormElement extends Components.AcmeContactForm, HTMLStencilElement {
    }
    var HTMLAcmeContactFormElement: {
        prototype: HTMLAcmeContactFormElement;
        new (): HTMLAcmeContactFormElement;
    };
    interface HTMLAcmeFooterElement extends Components.AcmeFooter, HTMLStencilElement {
    }
    var HTMLAcmeFooterElement: {
        prototype: HTMLAcmeFooterElement;
        new (): HTMLAcmeFooterElement;
    };
    interface HTMLAcmeHeaderElement extends Components.AcmeHeader, HTMLStencilElement {
    }
    var HTMLAcmeHeaderElement: {
        prototype: HTMLAcmeHeaderElement;
        new (): HTMLAcmeHeaderElement;
    };
    interface HTMLAcmeNavbarElement extends Components.AcmeNavbar, HTMLStencilElement {
    }
    var HTMLAcmeNavbarElement: {
        prototype: HTMLAcmeNavbarElement;
        new (): HTMLAcmeNavbarElement;
    };
    interface HTMLAcmeSectionsElement extends Components.AcmeSections, HTMLStencilElement {
    }
    var HTMLAcmeSectionsElement: {
        prototype: HTMLAcmeSectionsElement;
        new (): HTMLAcmeSectionsElement;
    };
    interface HTMLAcmeSubnavElement extends Components.AcmeSubnav, HTMLStencilElement {
    }
    var HTMLAcmeSubnavElement: {
        prototype: HTMLAcmeSubnavElement;
        new (): HTMLAcmeSubnavElement;
    };
    interface HTMLAcmeWebsiteElement extends Components.AcmeWebsite, HTMLStencilElement {
    }
    var HTMLAcmeWebsiteElement: {
        prototype: HTMLAcmeWebsiteElement;
        new (): HTMLAcmeWebsiteElement;
    };
    interface HTMLBannerSectionElement extends Components.BannerSection, HTMLStencilElement {
    }
    var HTMLBannerSectionElement: {
        prototype: HTMLBannerSectionElement;
        new (): HTMLBannerSectionElement;
    };
    interface HTMLDivServizioElement extends Components.DivServizio, HTMLStencilElement {
    }
    var HTMLDivServizioElement: {
        prototype: HTMLDivServizioElement;
        new (): HTMLDivServizioElement;
    };
    interface HTMLElementTagNameMap {
        "acme-chat-button": HTMLAcmeChatButtonElement;
        "acme-contact-form": HTMLAcmeContactFormElement;
        "acme-footer": HTMLAcmeFooterElement;
        "acme-header": HTMLAcmeHeaderElement;
        "acme-navbar": HTMLAcmeNavbarElement;
        "acme-sections": HTMLAcmeSectionsElement;
        "acme-subnav": HTMLAcmeSubnavElement;
        "acme-website": HTMLAcmeWebsiteElement;
        "banner-section": HTMLBannerSectionElement;
        "div-servizio": HTMLDivServizioElement;
    }
}
declare namespace LocalJSX {
    interface AcmeChatButton {
    }
    interface AcmeContactForm {
    }
    interface AcmeFooter {
    }
    interface AcmeHeader {
    }
    interface AcmeNavbar {
    }
    interface AcmeSections {
    }
    interface AcmeSubnav {
    }
    interface AcmeWebsite {
    }
    interface BannerSection {
    }
    interface DivServizio {
        /**
          * service's description
         */
        "description"?: string;
        /**
          * attribute name to choose the ionicon
         */
        "iconName"?: string;
        /**
          * service's title
         */
        "label"?: string;
    }
    interface IntrinsicElements {
        "acme-chat-button": AcmeChatButton;
        "acme-contact-form": AcmeContactForm;
        "acme-footer": AcmeFooter;
        "acme-header": AcmeHeader;
        "acme-navbar": AcmeNavbar;
        "acme-sections": AcmeSections;
        "acme-subnav": AcmeSubnav;
        "acme-website": AcmeWebsite;
        "banner-section": BannerSection;
        "div-servizio": DivServizio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "acme-chat-button": LocalJSX.AcmeChatButton & JSXBase.HTMLAttributes<HTMLAcmeChatButtonElement>;
            "acme-contact-form": LocalJSX.AcmeContactForm & JSXBase.HTMLAttributes<HTMLAcmeContactFormElement>;
            "acme-footer": LocalJSX.AcmeFooter & JSXBase.HTMLAttributes<HTMLAcmeFooterElement>;
            "acme-header": LocalJSX.AcmeHeader & JSXBase.HTMLAttributes<HTMLAcmeHeaderElement>;
            "acme-navbar": LocalJSX.AcmeNavbar & JSXBase.HTMLAttributes<HTMLAcmeNavbarElement>;
            "acme-sections": LocalJSX.AcmeSections & JSXBase.HTMLAttributes<HTMLAcmeSectionsElement>;
            "acme-subnav": LocalJSX.AcmeSubnav & JSXBase.HTMLAttributes<HTMLAcmeSubnavElement>;
            "acme-website": LocalJSX.AcmeWebsite & JSXBase.HTMLAttributes<HTMLAcmeWebsiteElement>;
            "banner-section": LocalJSX.BannerSection & JSXBase.HTMLAttributes<HTMLBannerSectionElement>;
            "div-servizio": LocalJSX.DivServizio & JSXBase.HTMLAttributes<HTMLDivServizioElement>;
        }
    }
}
